name: docs
on:
  push:
    branches:
      - main
      - develop

jobs:
  docs:
    name: build and deploy docs
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: run mkdocs
        run: |
          cd docs
          mkdocs build
      - name: deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: docs/site
